name: maher_law
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  anim_search_bar: ^2.0.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  expandable_page_view: ^1.0.17
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  morphable_shape: ^2.0.0
  responsive_sizer: ^3.3.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #       - asset: assets/fonts/Cairo-SemiBold.ttf
