// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxltH58FKPbQdI_Q-GRgjyjG3oVTCwKo4',
    appId: '1:1006683624179:web:58a0fe5a67068e3cdcdd86',
    messagingSenderId: '1006683624179',
    projectId: 'maher-law',
    authDomain: 'maher-law.firebaseapp.com',
    storageBucket: 'maher-law.firebasestorage.app',
    measurementId: 'G-C3YYTMLQ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5DtvE5g3fDjJLkST6pz8RzXoHemKkCI',
    appId: '1:1006683624179:android:ca6f99adadc06d43dcdd86',
    messagingSenderId: '1006683624179',
    projectId: 'maher-law',
    storageBucket: 'maher-law.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuP88Ssli4FMRutel_Al6fwEy_4tLSA8o',
    appId: '1:1006683624179:ios:615f912f4155a5c5dcdd86',
    messagingSenderId: '1006683624179',
    projectId: 'maher-law',
    storageBucket: 'maher-law.firebasestorage.app',
    iosBundleId: 'com.example.maherLaw',
  );
}
